package io.github.droidkaigi.confsched2023.primitive

import kotlinx.kover.gradle.plugin.dsl.KoverReportExtension
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.kotlin.dsl.configure

class KoverPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        with(target) {
            pluginManager.apply("org.jetbrains.kotlinx.kover")

            configure<KoverReportExtension> {
                filters {
                    excludes {
                        packages(
                            "com.airbnb.android.showkase",
                            "dagger.hilt.*",
                            "hilt_aggregated_deps",
                        )
                        classes(
                            // classes generated by Hilt
                            "Hilt_*",
                            "*_Factory",
                            "*_HiltModules*",
                            "*Module_Provide*Factory",
                            // compose previews
                            "*Preview*Kt",
                        )
                    }
                }
            }
        }
    }
}
