disabled_rules:
  - line_length
  - type_name
  - trailing_comma

opt_in_rules:
  - file_header
  - sorted_imports

included:
  - App/DroidKaigi2023
  - Modules/Package.swift
  - Modules/Sources
  - Modules/Tests

identifier_name:
  min_length: 2

# Why is this rule needed?
# please refer to https://github.com/DroidKaigi/conference-app-2020/pull/447#discussion_r368300240
file_header:
  severity: warning
  forbidden_pattern: ^(?!// Workaround:)
