name: 'Setup JDK'

inputs:
  java-version:
    description: "Java version. Just for DRY inside of this file."
    default: "17"

runs:
  using: "composite"
  steps:
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # v1.1.0

    - name: Copy CI gradle.properties
      shell: bash
      run: |
        mkdir -p ~/.gradle
        cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}

    # Better than caching and/or extensions of actions/setup-java
    - name: Setup Gradle
      uses: gradle/gradle-build-action@a4cf152f482c7ca97ef56ead29bf08bcd953284c # v2.7.0
      with:
        gradle-version: wrapper
