package io.github.droidkaigi.confsched2023.designsystem.theme

import androidx.compose.ui.graphics.Color

// Generated code from https://m3.material.io/theme-builder#/custom

val md_theme_light_primary = Color(0xFF006C50)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF85F8CC)
val md_theme_light_onPrimaryContainer = Color(0xFF002116)
val md_theme_light_secondary = Color(0xFF4C6359)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCEE9DB)
val md_theme_light_onSecondaryContainer = Color(0xFF092017)
val md_theme_light_tertiary = Color(0xFF3F6374)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC2E8FD)
val md_theme_light_onTertiaryContainer = Color(0xFF001F2A)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFDF9)
val md_theme_light_onBackground = Color(0xFF191C1A)
val md_theme_light_surface = Color(0xFFF8FAF6)
val md_theme_light_onSurface = Color(0xFF191C1A)
val md_theme_light_surfaceVariant = Color(0xFFDBE5DE)
val md_theme_light_onSurfaceVariant = Color(0xFF404944)
val md_theme_light_outline = Color(0xFF707974)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1EE)
val md_theme_light_inverseSurface = Color(0xFF2E312F)
val md_theme_light_inversePrimary = Color(0xFF67DBB1)
val md_theme_light_surfaceTint = Color(0xFF006C50)
val md_theme_light_outlineVariant = Color(0xFFBFC9C2)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF67DBB1)
val md_theme_dark_onPrimary = Color(0xFF003828)
val md_theme_dark_primaryContainer = Color(0xFF00513B)
val md_theme_dark_onPrimaryContainer = Color(0xFF85F8CC)
val md_theme_dark_secondary = Color(0xFFB3CCBF)
val md_theme_dark_onSecondary = Color(0xFF1E352C)
val md_theme_dark_secondaryContainer = Color(0xFF354B41)
val md_theme_dark_onSecondaryContainer = Color(0xFFCEE9DB)
val md_theme_dark_tertiary = Color(0xFFA6CCE0)
val md_theme_dark_onTertiary = Color(0xFF093544)
val md_theme_dark_tertiaryContainer = Color(0xFF264B5C)
val md_theme_dark_onTertiaryContainer = Color(0xFFC2E8FD)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1A)
val md_theme_dark_onBackground = Color(0xFFE1E3DF)
val md_theme_dark_surface = Color(0xFF111412)
val md_theme_dark_onSurface = Color(0xFFC5C7C4)
val md_theme_dark_surfaceVariant = Color(0xFF404944)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC9C2)
val md_theme_dark_outline = Color(0xFF89938D)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1A)
val md_theme_dark_inverseSurface = Color(0xFFE1E3DF)
val md_theme_dark_inversePrimary = Color(0xFF006C50)
val md_theme_dark_surfaceTint = Color(0xFF67DBB1)
val md_theme_dark_outlineVariant = Color(0xFF404944)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF006C50)

val arcticfoxBlue = Color(0xFF0A57A4)
val bumblebeeYellow = Color(0xFF5E5504)
val chipmunkBrown = Color(0xFF552E21)
val dolphinGreen = Color(0xFF026066)
val electriceelGray = Color(0xFF494E5A)
val arcticfoxBluePale = Color(0xFFB2D1FF)
val bumblebeeYellowPale = Color(0xFFF0DF63)
val chipmunkBrownPale = Color(0xFFE7BB92)
val dolphinGreenPale = Color(0xFFB4DDDD)
val electriceelGrayPale = Color(0xFFB8B9BD)

val md_theme_light_floor_button_background = Color(0xFFFFFFFF)

val md_theme_dark_floor_button_background = Color(0xFF000000)
