on:
  push:
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'

name: "Actionlint"

run-name: "Run ActionLint by ${{ github.actor }}"

permissions: {}

jobs:
  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - uses: jaxxstorm/action-install-gh-release@c5ead9a448b4660cf1e7866ee22e4dc56538031a #v1.10.0
        with:
          repo: rhysd/actionlint
          tag: "v1.6.25"
          cache: enable
  
      - name: Run actionlint
        run: actionlint -color
