name: iOS Lint

on:
  pull_request:
    paths:
      - 'app-ios/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:0.52.4

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 1

      - name: SwiftLint
        run: cd app-ios && swiftlint lint --reporter github-actions-logging
