name: "cache SPM"
description: "save and restore SPM cache"
runs:
  using: "composite"
  steps:
    - uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
      id: cache-spm
      with:
        path: |
          ./app-ios/build/DerivedData/SourcePackages
        key: v1-spm-${{ runner.os }}-${{ hashFiles('.xcode-version') }}-${{ hashFiles('app-ios/Modules/Package.swift') }}-${{ hashFiles('app-ios/App/DroidKaigi2023/DroidKaigi2023.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}

    - if: ${{ steps.cache-spm.outputs.cache-hit != 'true' }}
      shell: bash
      working-directory: app-ios
      run: bundle exec fastlane shared

    - if: ${{ steps.cache-spm.outputs.cache-hit != 'true' }}
      shell: bash
      working-directory: app-ios
      run: bundle exec fastlane resolved_package

    - if: ${{ steps.cache-spm.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
      with:
        path: |
          ./app-ios/build/DerivedData/SourcePackages
        key: v1-spm-${{ runner.os }}-${{ hashFiles('.xcode-version') }}-${{ hashFiles('app-ios/Modules/Package.swift') }}-${{ hashFiles('app-ios/App/DroidKaigi2023/DroidKaigi2023.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
